name: Deploy FastAPI to Azure Web App (zip + persistent venv)

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      # Cache speeds up tests/lint locally in CI only (not App Service)
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      # (Optional) quick sanity checks
      - run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          python -c "import sys; print('✅ CI sanity OK', sys.version)"

      # Create deployment zip with ONLY app code (no venv)
      - name: Build artifact (zip)
        run: |
          mkdir -p build
          zip -r build/app.zip . \
            -x ".git/*" \
               ".github/*" \
               "__pycache__/*" \
               ".venv/*" "venv/*" \
               "build/*"

      # Azure login (uses OIDC; set up Federated Credentials in Azure)
      - uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_06397A9FB8C64E0ABBBDE56CB0738486 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_4BF4323FFE9B4B7AAC9B5BC9AD035743 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_E0A9222A95A34D54A35272CA12F4AA5B }}

      # Deploy zip (this is fast; dependencies are handled by startup.sh on the server)
      - name: Zip Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'rahul-webapp-clean'
          slot-name: 'Production'
          